version: '3.1'

services: 
  my-registry:
    image: registry:2.7.1
    volumes: 
      - registry:/var/lib/registry
    ports:
      - "5000:5000"
    restart: unless-stopped
    
volumes: 
  registry: