version: '3.1'

services:
  generator:
    image: my-registry:5000/gen:ci-${GENAPP_BUILD_NUMBER-10}
    networks: 
      - integration-test-network
    #ports:
    #  - "8080:80"
  mail:
    image: mailhog/mailhog
    networks: 
      - integration-test-network
    #ports:
    #  - "8025:8025"
  integration-test:
    build:
      context: .
    image: my-registry:5000/integration-${BUILD_NUMBER-10}
    environment:
      TEAMCITY_PROJECT_NAME: ${TEAMCITY_PROJECT_NAME-fake}
    networks: 
      - integration-test-network
networks:
  integration-test-network: {}